#!/bin/bash
# Compute addresses for all units from example-units-input.yml
# Generates _data/example-units.yml with addresses for Jekyll
# Usage: ./compute-all-addresses.sh [rpc-url]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INPUT_FILE="$SCRIPT_DIR/../_data/example-units-input.yml"
OUTPUT_FILE="$SCRIPT_DIR/../_data/example-units.yml"
RPC_URL="${1:-https://ethereum.publicnode.com}"

if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: Input file not found: $INPUT_FILE" >&2
    exit 1
fi

# Check for yq
if ! command -v yq &> /dev/null; then
    echo "Error: yq is required but not installed" >&2
    echo "Install with: brew install yq (macOS) or snap install yq (Linux)" >&2
    exit 1
fi

echo "Computing addresses for units from: $INPUT_FILE"
echo "RPC: $RPC_URL"
echo "Output: $OUTPUT_FILE"
echo ""

# First, validate all units
if ! "$SCRIPT_DIR/validate-all-units.sh" "$RPC_URL"; then
    echo "Error: Validation failed. Cannot compute addresses for non-canonical symbols." >&2
    exit 1
fi

echo ""
echo "All units validated. Computing addresses..."
echo ""

# Start building output YAML
cat > "$OUTPUT_FILE" << 'EOF'
# Example Units with Computed Addresses
# Generated by scripts/compute-all-addresses.sh
# DO NOT EDIT MANUALLY - Edit _data/example-units-input.yml instead

units:
EOF

# Process each unit
unit_count=$(yq eval '.units | length' "$INPUT_FILE")

for ((i=0; i<unit_count; i++)); do
    symbol=$(yq eval ".units[$i].symbol" "$INPUT_FILE")
    description=$(yq eval ".units[$i].description" "$INPUT_FILE")

    if [ -z "$symbol" ]; then
        continue
    fi

    echo "Computing: $symbol"

    # Get address and canonical form
    result=$("$SCRIPT_DIR/compute-unit-address.sh" "$symbol" "$RPC_URL")

    if [ $? -ne 0 ]; then
        echo "Error: Failed to compute address for $symbol" >&2
        exit 1
    fi

    # Parse JSON result
    address=$(echo "$result" | jq -r '.address')
    canonical=$(echo "$result" | jq -r '.canonical')

    # Append to output file
    cat >> "$OUTPUT_FILE" << EOF
  - symbol: "$symbol"
    canonical: "$canonical"
    address: "$address"
    one: "$one"
    description: "$description"

EOF

    # Rate limit
    sleep 0.3
done

echo ""
echo "✅ Address computation complete!"
echo "Output written to: $OUTPUT_FILE"
echo ""
echo "Unit count: $unit_count"
